#!/usr/bin/env python3
"""Extracts Microsoft's per-check markdown docs (background + remediation links) from the
upstream zerotrustassessment repo into js/checkDocs.js.

Usage:  python3 scripts/extract-check-docs.py /path/to/microsoft-zerotrustassessment-clone
Re-run on upstream releases to refresh the docs.
"""
import json, re, sys, pathlib

# our check id -> upstream TestId ('~' prefix = related check, background only)
MAPPING = {
    'ZTA-002': '21796',  'ZTA-003': '~21800', 'ZTA-005': '21783',  'ZTA-006': '21799',
    'ZTA-007': '21835',  'ZTA-008': '21776',  'ZTA-010': '21791',  'ZTA-011': '21792',
    'ZTA-012': '21812',  'ZTA-014': '~21801', 'ZTA-015': '21865',  'ZTA-016': '21811',
    'ZTA-017': '21809',  'ZTA-018': '~21774', 'ZTA-019': '21851',  'ZTA-020': '24824',
    'ZTA-021': '21825',  'ZTA-023': '21858',  'ZTA-024': '~21817', 'ZTA-025': '21893',
    'ZTA-101': '~24541',
}

upstream = pathlib.Path(sys.argv[1]) / 'src/powershell/tests'
docs, meta = {}, {}
for zta, tid in MAPPING.items():
    approx = tid.startswith('~'); tid = tid.lstrip('~')
    p = upstream / f'Test-Assessment.{tid}.md'
    if not p.exists():
        print(f'!! missing {p}', file=sys.stderr); continue
    md = p.read_text(encoding='utf-8-sig', errors='replace')
    md = md.split('<!--- Results --->')[0].replace('%TestResult%', '').strip()
    parts = re.split(r'\*\*Remediation action(?:s)?\*\*', md, maxsplit=1)
    bg = parts[0].strip()
    rem = []
    if len(parts) > 1:
        for m in re.finditer(r'\[([^\]]+)\]\((https?://[^)]+)\)', parts[1]):
            rem.append([m.group(1), m.group(2)])
    docs[zta] = {'ztId': tid, 'approx': approx, 'bg': bg, 'rem': rem}
print(f'{len(docs)} docs extracted')

out = pathlib.Path(__file__).resolve().parent.parent / 'js' / 'checkDocs.js'
out.parent.mkdir(exist_ok=True)
out.write_text(
    '// GENERATED by scripts/extract-check-docs.py — background docs from the MIT-licensed\n'
    '// https://github.com/microsoft/zerotrustassessment — do not edit by hand.\n'
    'window.CHECK_DOCS = ' + json.dumps(docs, ensure_ascii=False, indent=1) + ';\n',
    encoding='utf-8')
print(f'wrote {out}')
